### ISSUE TITLE
Module is not working with paypal express checkout 

### ISSUE THREAD

**Issue by ankursharma1930** [mageprince/magento2-extrafee#23] opened 2018-10-03 06:13 UTC
Custom fees is adding in grandTotal but somehow it's showing error in paypal express, please refer the screenshot.
Note:- i have also disabled the "Transfer Cart Line Items" in paypal additional settings, but it still throwing error.
![screenshot 4](https://user-images.githubusercontent.com/16528097/46393070-57660a80-c701-11e8-9f2f-422f96b53e97.png)

**Comment by mageprince** [comment] 2018-10-16 10:25
@ankursharma1930 Thank you for your report.
I am closing this issue as a duplicate of #22

**Closed as completed by mageprince** 2018-10-16 10:25 UTC
